# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: P@ssword1!
    ports:
      - 5432:5432
  web:
    image: nginx
    volumes:
      - ./nginx/default:/etc/nginx/templates
      - ./Frontend/dist:/var/www/ui-static
      - ./Backend/uploads:/var/www/my-collection/uploads
    ports:
      - '8080:80'
    environment:
      - NGINX_PORT=80
