name: Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.SECRET }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      - run: yarn install
        working-directory: ./Frontend
      - run: yarn generate
        working-directory: ./Frontend
      - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@45.89.66.152:/opt/www/my-collection/ui
        working-directory: ./Frontend/.output/public
      - run: npm install
        working-directory: ./Backend
      - run: npm run build
        working-directory: ./Backend
        env:
          NODE_ENV: develop
      - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@45.89.66.152:/opt/www/my-collection/api
        working-directory: ./Backend/dist
